//////////// TRAE LAS CATEGORIAS ////////////

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR"
export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR"
export const SAVE_CATEGORY_REQUEST = "SAVE_CATEGORY_REQUEST";
export const SAVE_CATEGORY_SUCCESS = "SAVE_CATEGORY_SUCCESS";
export const SAVE_CATEGORY_ERROR = "SAVE_CATEGORY_ERROR";
export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";


//////////// TRAE LOS PRODUCTOS PARA MOSTRAR EN HOME ////////////

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCSSES";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCTS_SUCSSES";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCTS_ERROR"
export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_ERROR = "SAVE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";


//////////// TRAE LOS PRODUCTOS DE LA DB.CARRITO  ////////////

export const GET_PRODUCTS_FROM_CART_REQUEST = "GET_PRODUCTS_FROM_CART_REQUEST";
export const GET_PRODUCTS_FROM_CART_SUCCESS = "GET_PRODUCTS_FROM_CART_SUCCESS";
export const GET_PRODUCTS_FROM_CART_ERROR = "GET_PRODUCTS_FROM_CART_ERROR";


//////////// AGREGA LOS PRODUCTOS A LA DB.CARRITO  ////////////

export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_ERROR = 'CART_ADD_ITEM_ERROR';

//////////// ELIMINA UN PRODUCT DE LA DB.CARRITO  ////////////

export const CART_DELETE_ITEM_REQUEST = 'CART_DELETE_ITEM_REQUEST';
export const CART_DELETE_ITEM_SUCCESS = 'CART_DELETE_ITEM_SUCCESS';
export const CART_DELETE_ITEM_ERROR = 'CART_DELETE_ITEM_ERROR';

//////////// RESTAR UN PRODUCT DE LA DB.CARRITO  ////////////

export const CART_SUBSTRACT_ITEM_REQUEST = 'CART_SUBSTRACT_ITEM_REQUEST';
export const CART_SUBSTRACT_ITEM_SUCCESS = 'CART_SUBSTRACT_ITEM_SUCCESS';
export const CART_SUBSTRACT_ITEM_ERROR = 'CART_SUBSTRACT_ITEM_ERROR';